version: '3.1'

services:

    node:
        build: ./
        restart: always
        depends_on:
            - db
        ports:
            - 8000:8000
        volumes:
            - .:/Users/lisouiw/42/DressMe/server
            - /Users/lisouiw/42/DressMe/server/node_modules
        links:
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dressme