version: "3.1"

services:
  node:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: server_node
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/Users/lisouiw/42/DressMe/server
  db:
    image: postgres:latest
    container_name: server_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dressme
    depends_on:
      - node
